### ISSUE TITLE
Font Language Supporting in SAO

### ISSUE THREAD

**Issue by ALiwoto** [TeaInside/SAO#1]
**Languages in SAO**

-> currently the only languages supported in the game, is English,
but I'm planing to support Japanese as well.

Which is _why_ I added these assemblies in the /references directory:

1. Cyotek.Drawing.BitmapFont.dll
2. FontStashSharp.MonoGame.dll
3. StbImageSharp.dll
4. StbTrueTypeSharp.dll

That's why we don't need .xnb files in /F_M_G directory anymore.
But, there's a probability that windows platform don't support these texture drawing (I've already tested them in linux-x64, there is no problem here), so we have to test them in another platform as well.

**Comment by ALiwoto** [comment]
I think it's better to remove .xnb font compiled files from `/F_M_G` directory then.

**Comment by ArthuriaDX** [comment]
@ALiwoto Just remove them.
But you have to also update the code in FontManager.cs.
I think it's better to load the fonts from Embedded Resources (in .resx file).

**Comment by ALiwoto** [comment]
done
