### ISSUE TITLE
Current directory path of the game.

### ISSUE THREAD

**Issue by ALiwoto** [TeaInside/SAO#4]
The definition of the static property `ThereIsConstants.Path.Here` is like this:

```
public static StrongString Here
{
	//get => Directory.GetCurrentDirectory();
	get => AppContext.BaseDirectory;
}
```
As you can see, I commented the `Directory.GetCurrentDirectory()`.
We will use `AppContext.BaseDirectory` from now on, it means that using of the `GetCurrentDirectory()` in the game is prohibited from now on.
The reason is that the `GetCurrentDirectory()` won't give you the **Actual** path of the game.
For example in linux, if you enter following commands in the terminal:
`$ cd ~`
`$ <Path_to_project>/SAO/bin/Debug/net5.0/linux-x64/SAO`,
in this case, `Directory.GetCurrentDirectory()`, won't give you `<Path_to_project>/SAO/bin/Debug/net5.0/linux-x64`, rather it will give you your home path.

And one another thing:
`Directory.GetCurrentDirectory()` didn't use slash (or back slash in windows), so we **had** to attach it to the value.
However `AppContext.BaseDirectory` will use it in the end of the string, so we all codes like this:
`ThereIsConstants.Path.Here + ThereIsConstants.Path.USlash + ...`
**should** be edited.

**Comment by ArthuriaDX** [comment]
@ALiwoto It's really a big mistake to use ``StrongString`` for that.
You used it in the ``ThereIsConstants.Actions.IsSingleOne()``, right?
Exactly before you create the ``DECoder``.
I think it's better to consider using ``string``.

**Comment by ALiwoto** [comment]
@ArthuriaDX right, so we have to set ``DECoder`` before that, right?

**Comment by ArthuriaDX** [comment]
@ALiwoto What if ``ThereIsConstants.Actions.IsSingleOne()`` returns ``false`` then?
You just wanna use more resources, huh?
Make things simpler, it's better to be a simple ``string``.

**Comment by ALiwoto** [comment]
@ArthuriaDX okay, done
