### ISSUE TITLE
Moving Graphic Elements Algorithm

### ISSUE THREAD

**Issue by ALiwoto** [TeaInside/SAO#8]
I believe The algorithm used for `MoveManger` is not correct.
when you are trying to move the elements, it works fine, but when you try to move them behind another elements, they won't work correctly.
we have to work on it.

**Comment by ALiwoto** [comment]
I just can't figure it out where did I go wrong ....
hmmmm, let's see, it will took more time it seems

**Comment by ArthuriaDX** [comment]
@ALiwoto No need to hurry, don't worry about it.

**Comment by ALiwoto** [comment]
okay done, I solved the problem in the algorithm.

**Comment by ALiwoto** [comment]
I'll close the issue then
it really took more than time that I imagined
